//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gitle.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("Gitle.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activeer.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string Address_City_Help {
            get {
                return ResourceManager.GetString("Address_City_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer.
        /// </summary>
        public static string Address_Housenumber {
            get {
                return ResourceManager.GetString("Address_Housenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen het nummer.
        /// </summary>
        public static string Address_Housenumber_Help {
            get {
                return ResourceManager.GetString("Address_Housenumber_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoeging.
        /// </summary>
        public static string Address_HousenumberExtension {
            get {
                return ResourceManager.GetString("Address_HousenumberExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventueele toevoeging.
        /// </summary>
        public static string Address_HousenumberExtension_Help {
            get {
                return ResourceManager.GetString("Address_HousenumberExtension_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerking.
        /// </summary>
        public static string Address_Note {
            get {
                return ResourceManager.GetString("Address_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evt. Bijzonderheden bij het ophalen.
        /// </summary>
        public static string Address_Note_Help {
            get {
                return ResourceManager.GetString("Address_Note_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straat.
        /// </summary>
        public static string Address_Street {
            get {
                return ResourceManager.GetString("Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straatnaam.
        /// </summary>
        public static string Address_Street_Help {
            get {
                return ResourceManager.GetString("Address_Street_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Address_Zipcode {
            get {
                return ResourceManager.GetString("Address_Zipcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode formaat: &apos;1111 XX&apos;.
        /// </summary>
        public static string Address_Zipcode_Help {
            get {
                return ResourceManager.GetString("Address_Zipcode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gitle.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiveer.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to om.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen niet gelukt.
        /// </summary>
        public static string Authenticate_Failed {
            get {
                return ResourceManager.GetString("Authenticate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wijzig.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wis zoekresultaten.
        /// </summary>
        public static string Clear_Search {
            get {
                return ResourceManager.GetString("Clear_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compleet.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klant.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actieve Klanten.
        /// </summary>
        public static string Customer_Active {
            get {
                return ResourceManager.GetString("Customer_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klant toevoegen.
        /// </summary>
        public static string Customer_Add {
            get {
                return ResourceManager.GetString("Customer_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereiding diner.
        /// </summary>
        public static string Customer_CanCookAlone {
            get {
                return ResourceManager.GetString("Customer_CanCookAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of de klant zelfstandig diner kan bereiden of hierbij ondersteuning nodig heeft.
        /// </summary>
        public static string Customer_CanCookAlone_Help {
            get {
                return ResourceManager.GetString("Customer_CanCookAlone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vervoer.
        /// </summary>
        public static string Customer_CanDriveAlone {
            get {
                return ResourceManager.GetString("Customer_CanDriveAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of de klant zelfstandig kan rijden of hierbij ondersteuning nodig heeft.
        /// </summary>
        public static string Customer_CanDriveAlone_Help {
            get {
                return ResourceManager.GetString("Customer_CanDriveAlone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boodschappen doen.
        /// </summary>
        public static string Customer_CanShopAlone {
            get {
                return ResourceManager.GetString("Customer_CanShopAlone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of de klant zelfstandig boodschappen kan doen of hierbij ondersteuning nodig heeft.
        /// </summary>
        public static string Customer_CanShopAlone_Help {
            get {
                return ResourceManager.GetString("Customer_CanShopAlone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afspraak maken.
        /// </summary>
        public static string Customer_Create_Match {
            get {
                return ResourceManager.GetString("Customer_Create_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeur dagen.
        /// </summary>
        public static string Customer_DayPreference {
            get {
                return ResourceManager.GetString("Customer_DayPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies de voorkeur dag(en) van de klant.
        /// </summary>
        public static string Customer_DayPreference_Help {
            get {
                return ResourceManager.GetString("Customer_DayPreference_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieetwensen.
        /// </summary>
        public static string Customer_DietaryRequirements {
            get {
                return ResourceManager.GetString("Customer_DietaryRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier de dieetwensen in. Bijv. vegetarisch, halal, zoutarm, e.d..
        /// </summary>
        public static string Customer_DietaryRequirements_Help {
            get {
                return ResourceManager.GetString("Customer_DietaryRequirements_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewerk klant.
        /// </summary>
        public static string Customer_Edit {
            get {
                return ResourceManager.GetString("Customer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorkeur samenstelling groep.
        /// </summary>
        public static string Customer_GroupCompositionPreference {
            get {
                return ResourceManager.GetString("Customer_GroupCompositionPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies de voorkeur voor de samenstelling van de groep: 60+ of alle leeftijden.
        /// </summary>
        public static string Customer_GroupCompositionPreference_Help {
            get {
                return ResourceManager.GetString("Customer_GroupCompositionPreference_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegankelijkheid woning.
        /// </summary>
        public static string Customer_HomeAccessibility {
            get {
                return ResourceManager.GetString("Customer_HomeAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan voor welke mobiliteiten de woning geschikt is.
        /// </summary>
        public static string Customer_HomeAccessibility_Help {
            get {
                return ResourceManager.GetString("Customer_HomeAccessibility_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De woning is toegankelijk voor.
        /// </summary>
        public static string Customer_HomeAccessibility_Label {
            get {
                return ResourceManager.GetString("Customer_HomeAccessibility_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisbezoek.
        /// </summary>
        public static string Customer_HouseVisit {
            get {
                return ResourceManager.GetString("Customer_HouseVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan of deze klant een huisbezoek wenst.
        /// </summary>
        public static string Customer_HouseVisit_Help {
            get {
                return ResourceManager.GetString("Customer_HouseVisit_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja, deze klant wenst een huisbezoek.
        /// </summary>
        public static string Customer_HouseVisit_Label {
            get {
                return ResourceManager.GetString("Customer_HouseVisit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum van huisbezoek.
        /// </summary>
        public static string Customer_HouseVisitDate {
            get {
                return ResourceManager.GetString("Customer_HouseVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan op welke datum deze klant een huisbezoek wenst.
        /// </summary>
        public static string Customer_HouseVisitDate_Help {
            get {
                return ResourceManager.GetString("Customer_HouseVisitDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearchiveerde klanten.
        /// </summary>
        public static string Customer_InActive {
            get {
                return ResourceManager.GetString("Customer_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiliteit.
        /// </summary>
        public static string Customer_Mobility {
            get {
                return ResourceManager.GetString("Customer_Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier eventuele mobiliteitsproblemen van de klant in. Bijv. rollator, inklapbare rolstoel, rolstoelgebonden e.d..
        /// </summary>
        public static string Customer_Mobility_Help {
            get {
                return ResourceManager.GetString("Customer_Mobility_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijvingsdatum.
        /// </summary>
        public static string Customer_RegisterDate {
            get {
                return ResourceManager.GetString("Customer_RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer is deze persoon ingeschreven is in het systeem..
        /// </summary>
        public static string Customer_RegisterDate_Help {
            get {
                return ResourceManager.GetString("Customer_RegisterDate_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingeschreven door.
        /// </summary>
        public static string Customer_RegisteredBy {
            get {
                return ResourceManager.GetString("Customer_RegisteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De persoon die deze klant heeft ingeschreven.
        /// </summary>
        public static string Customer_RegisteredBy_Help {
            get {
                return ResourceManager.GetString("Customer_RegisteredBy_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijving.
        /// </summary>
        public static string Customer_Registration {
            get {
                return ResourceManager.GetString("Customer_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klanten.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestemmingen.
        /// </summary>
        public static string Destinations {
            get {
                return ResourceManager.GetString("Destinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporteer.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijdag.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groep.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewenst aantal leden.
        /// </summary>
        public static string Group_CompleteCount {
            get {
                return ResourceManager.GetString("Group_CompleteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groepsleden.
        /// </summary>
        public static string Group_Customers {
            get {
                return ResourceManager.GetString("Group_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze groep is compleet.
        /// </summary>
        public static string Group_Make_Complete {
            get {
                return ResourceManager.GetString("Group_Make_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer.
        /// </summary>
        public static string Group_Number {
            get {
                return ResourceManager.GetString("Group_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle leeftijden.
        /// </summary>
        public static string GroupCompositionPreference_AllAges {
            get {
                return ResourceManager.GetString("GroupCompositionPreference_AllAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60+.
        /// </summary>
        public static string GroupCompositionPreference_SixtyPlus {
            get {
                return ResourceManager.GetString("GroupCompositionPreference_SixtyPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groepen.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zelfstandig.
        /// </summary>
        public static string Independently {
            get {
                return ResourceManager.GetString("Independently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingelogd blijven.
        /// </summary>
        public static string Login_Persistent {
            get {
                return ResourceManager.GetString("Login_Persistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maandag.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maand.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een maand.
        /// </summary>
        public static string Month_Help {
            get {
                return ResourceManager.GetString("Month_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhr..
        /// </summary>
        public static string Mr {
            get {
                return ResourceManager.GetString("Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mw..
        /// </summary>
        public static string Ms {
            get {
                return ResourceManager.GetString("Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string Name_Firstname {
            get {
                return ResourceManager.GetString("Name_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string Name_Firstname_Help {
            get {
                return ResourceManager.GetString("Name_Firstname_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht.
        /// </summary>
        public static string Name_Gender {
            get {
                return ResourceManager.GetString("Name_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht.
        /// </summary>
        public static string Name_Gender_Help {
            get {
                return ResourceManager.GetString("Name_Gender_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorletters.
        /// </summary>
        public static string Name_Initials {
            get {
                return ResourceManager.GetString("Name_Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorletters.
        /// </summary>
        public static string Name_Initials_Help {
            get {
                return ResourceManager.GetString("Name_Initials_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string Name_Lastname {
            get {
                return ResourceManager.GetString("Name_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam zonder tussenvoegsel.
        /// </summary>
        public static string Name_Lastname_Help {
            get {
                return ResourceManager.GetString("Name_Lastname_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel.
        /// </summary>
        public static string Name_Middlename {
            get {
                return ResourceManager.GetString("Name_Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tussenvoegsel o.a. : &apos;van&apos; enz..
        /// </summary>
        public static string Name_Middlename_Help {
            get {
                return ResourceManager.GetString("Name_Middlename_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondersteuning nodig.
        /// </summary>
        public static string NeedsSupport {
            get {
                return ResourceManager.GetString("NeedsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nee.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerking.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Person_Address {
            get {
                return ResourceManager.GetString("Person_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbaarheid.
        /// </summary>
        public static string Person_Availability {
            get {
                return ResourceManager.GetString("Person_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschikbaarheid opmerkingen.
        /// </summary>
        public static string Person_AvailabilityNote {
            get {
                return ResourceManager.GetString("Person_AvailabilityNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier alle extra informatie in m.b.t. beschikbaarheid..
        /// </summary>
        public static string Person_AvailabilityNote_Help {
            get {
                return ResourceManager.GetString("Person_AvailabilityNote_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact informatie.
        /// </summary>
        public static string Person_ContactInformation {
            get {
                return ResourceManager.GetString("Person_ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum.
        /// </summary>
        public static string Person_DateOfBirth {
            get {
                return ResourceManager.GetString("Person_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen geldige datum.
        /// </summary>
        public static string Person_DateOfBirth_Error {
            get {
                return ResourceManager.GetString("Person_DateOfBirth_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum van de persoon.
        /// </summary>
        public static string Person_DateOfBirth_Help {
            get {
                return ResourceManager.GetString("Person_DateOfBirth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emailadres.
        /// </summary>
        public static string Person_Email {
            get {
                return ResourceManager.GetString("Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voer hier het emailadres in.
        /// </summary>
        public static string Person_Email_Help {
            get {
                return ResourceManager.GetString("Person_Email_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Person_Name {
            get {
                return ResourceManager.GetString("Person_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerkingen.
        /// </summary>
        public static string Person_Note {
            get {
                return ResourceManager.GetString("Person_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul hier alle niet geclassificeerde informatie in..
        /// </summary>
        public static string Person_Note_Help {
            get {
                return ResourceManager.GetString("Person_Note_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string Person_Phone {
            get {
                return ResourceManager.GetString("Person_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer, bijv. 0612345678.
        /// </summary>
        public static string Person_Phone_Help {
            get {
                return ResourceManager.GetString("Person_Phone_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord aanvragen.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaterdag.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek een klant.
        /// </summary>
        public static string Search_Customer {
            get {
                return ResourceManager.GetString("Search_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afmelden.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zondag.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ondersteuning geregeld.
        /// </summary>
        public static string SupportIsArranged {
            get {
                return ResourceManager.GetString("SupportIsArranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donderdag.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dinsdag.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijwilliger.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woensdag.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een jaar.
        /// </summary>
        public static string Year_Help {
            get {
                return ResourceManager.GetString("Year_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
