/*
Deployment script for Gitle_Live

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Gitle_Live"
:setvar DefaultFilePrefix "Gitle_Live"
:setvar DefaultDataPath "D:\MSSQL\"
:setvar DefaultLogPath "D:\MSSQL\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering [dbo].[Project]...';


GO
ALTER TABLE [dbo].[Project]
    ADD [Application_id]           BIGINT         NULL,
        [Type]                     NVARCHAR (255) NULL,
        [BudgetMinutes]            FLOAT (53)     NULL,
        [TicketRequiredForBooking] BIT            NULL;


GO
PRINT N'Altering [dbo].[User]...';


GO
ALTER TABLE [dbo].[User]
    ADD [IsDanielle] BIT NULL;


GO
PRINT N'Creating [dbo].[Application]...';


GO
CREATE TABLE [dbo].[Application] (
    [Id]          BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]        UNIQUEIDENTIFIER NULL,
    [IsActive]    BIT              NULL,
    [Name]        NVARCHAR (255)   NULL,
    [Customer_id] BIGINT           NULL,
    [Slug]        NVARCHAR (255)   NULL,
    [Comments]    NVARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Booking]...';


GO
CREATE TABLE [dbo].[Booking] (
    [Id]         BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]       UNIQUEIDENTIFIER NULL,
    [IsActive]   BIT              NULL,
    [CreatedAt]  DATETIME         NULL,
    [Date]       DATETIME         NULL,
    [Comment]    NVARCHAR (255)   NULL,
    [Minutes]    FLOAT (53)       NULL,
    [Project_id] BIGINT           NULL,
    [User_id]    BIGINT           NULL,
    [Issue_id]   BIGINT           NULL,
    [Unbillable] BIT              NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Correction]...';


GO
CREATE TABLE [dbo].[Correction] (
    [Id]          BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]        UNIQUEIDENTIFIER NULL,
    [IsActive]    BIT              NULL,
    [Description] NVARCHAR (255)   NULL,
    [Price]       FLOAT (53)       NULL,
    [Invoice_id]  BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Document]...';


GO
CREATE TABLE [dbo].[Document] (
    [Id]           BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]         UNIQUEIDENTIFIER NULL,
    [IsActive]     BIT              NULL,
    [Name]         NVARCHAR (255)   NULL,
    [Path]         NVARCHAR (255)   NULL,
    [DateUploaded] DATETIME         NULL,
    [User_id]      BIGINT           NULL,
    [Project_id]   BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Invoice]...';


GO
CREATE TABLE [dbo].[Invoice] (
    [Id]           BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]         UNIQUEIDENTIFIER NULL,
    [IsActive]     BIT              NULL,
    [CreatedAt]    DATETIME         NULL,
    [HourPrice]    INT              NULL,
    [Title]        NVARCHAR (255)   NULL,
    [Number]       NVARCHAR (255)   NULL,
    [VAT]          BIT              NULL,
    [Remarks]      NVARCHAR (255)   NULL,
    [State]        NVARCHAR (255)   NULL,
    [StartDate]    DATETIME         NULL,
    [EndDate]      DATETIME         NULL,
    [Project_id]   BIGINT           NULL,
    [CreatedBy_id] BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[InvoiceBooking]...';


GO
CREATE TABLE [dbo].[InvoiceBooking] (
    [Booking_id] BIGINT NOT NULL,
    [Invoice_id] BIGINT NOT NULL
);


GO
PRINT N'Creating [dbo].[InvoiceLine]...';


GO
CREATE TABLE [dbo].[InvoiceLine] (
    [Id]          BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]        UNIQUEIDENTIFIER NULL,
    [IsActive]    BIT              NULL,
    [Description] NVARCHAR (255)   NULL,
    [Hours]       FLOAT (53)       NULL,
    [Null]        BIT              NULL,
    [Invoice_id]  BIGINT           NULL,
    [Issue_id]    BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[ProjectDocument]...';


GO
CREATE TABLE [dbo].[ProjectDocument] (
    [Project_id]  BIGINT NOT NULL,
    [Document_id] BIGINT NOT NULL
);


GO
PRINT N'Creating [dbo].[ReportPreset]...';


GO
CREATE TABLE [dbo].[ReportPreset] (
    [Id]           BIGINT           IDENTITY (1, 1) NOT NULL,
    [Guid]         UNIQUEIDENTIFIER NULL,
    [IsActive]     BIT              NULL,
    [Name]         NVARCHAR (255)   NULL,
    [ReportString] NVARCHAR (255)   NULL,
    [User_id]      BIGINT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FK6AF3367D4487297D]...';


GO
ALTER TABLE [dbo].[Application] WITH NOCHECK
    ADD CONSTRAINT [FK6AF3367D4487297D] FOREIGN KEY ([Customer_id]) REFERENCES [dbo].[Customer] ([Id]);


GO
PRINT N'Creating [dbo].[FK4DB400AFC4985D11]...';


GO
ALTER TABLE [dbo].[Booking] WITH NOCHECK
    ADD CONSTRAINT [FK4DB400AFC4985D11] FOREIGN KEY ([Project_id]) REFERENCES [dbo].[Project] ([Id]);


GO
PRINT N'Creating [dbo].[FK4DB400AF2303E129]...';


GO
ALTER TABLE [dbo].[Booking] WITH NOCHECK
    ADD CONSTRAINT [FK4DB400AF2303E129] FOREIGN KEY ([User_id]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FK4DB400AF91F7CAB3]...';


GO
ALTER TABLE [dbo].[Booking] WITH NOCHECK
    ADD CONSTRAINT [FK4DB400AF91F7CAB3] FOREIGN KEY ([Issue_id]) REFERENCES [dbo].[Issue] ([Id]);


GO
PRINT N'Creating [dbo].[FK3232CB7E49E95258]...';


GO
ALTER TABLE [dbo].[Correction] WITH NOCHECK
    ADD CONSTRAINT [FK3232CB7E49E95258] FOREIGN KEY ([Invoice_id]) REFERENCES [dbo].[Invoice] ([Id]);


GO
PRINT N'Creating [dbo].[FKEF5E95782303E129]...';


GO
ALTER TABLE [dbo].[Document] WITH NOCHECK
    ADD CONSTRAINT [FKEF5E95782303E129] FOREIGN KEY ([User_id]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FKEF5E9578C4985D11]...';


GO
ALTER TABLE [dbo].[Document] WITH NOCHECK
    ADD CONSTRAINT [FKEF5E9578C4985D11] FOREIGN KEY ([Project_id]) REFERENCES [dbo].[Project] ([Id]);


GO
PRINT N'Creating [dbo].[FKDC60817C4985D11]...';


GO
ALTER TABLE [dbo].[Invoice] WITH NOCHECK
    ADD CONSTRAINT [FKDC60817C4985D11] FOREIGN KEY ([Project_id]) REFERENCES [dbo].[Project] ([Id]);


GO
PRINT N'Creating [dbo].[FKDC60817FEFE956F]...';


GO
ALTER TABLE [dbo].[Invoice] WITH NOCHECK
    ADD CONSTRAINT [FKDC60817FEFE956F] FOREIGN KEY ([CreatedBy_id]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FK9D9576249E95258]...';


GO
ALTER TABLE [dbo].[InvoiceBooking] WITH NOCHECK
    ADD CONSTRAINT [FK9D9576249E95258] FOREIGN KEY ([Invoice_id]) REFERENCES [dbo].[Invoice] ([Id]);


GO
PRINT N'Creating [dbo].[FK9D95762864FB2B8]...';


GO
ALTER TABLE [dbo].[InvoiceBooking] WITH NOCHECK
    ADD CONSTRAINT [FK9D95762864FB2B8] FOREIGN KEY ([Booking_id]) REFERENCES [dbo].[Booking] ([Id]);


GO
PRINT N'Creating [dbo].[FK64ABF92549E95258]...';


GO
ALTER TABLE [dbo].[InvoiceLine] WITH NOCHECK
    ADD CONSTRAINT [FK64ABF92549E95258] FOREIGN KEY ([Invoice_id]) REFERENCES [dbo].[Invoice] ([Id]);


GO
PRINT N'Creating [dbo].[FK64ABF92591F7CAB3]...';


GO
ALTER TABLE [dbo].[InvoiceLine] WITH NOCHECK
    ADD CONSTRAINT [FK64ABF92591F7CAB3] FOREIGN KEY ([Issue_id]) REFERENCES [dbo].[Issue] ([Id]);


GO
PRINT N'Creating [dbo].[FKC6101C91D8CDF7D2]...';


GO
ALTER TABLE [dbo].[ProjectDocument] WITH NOCHECK
    ADD CONSTRAINT [FKC6101C91D8CDF7D2] FOREIGN KEY ([Document_id]) REFERENCES [dbo].[Document] ([Id]);


GO
PRINT N'Creating [dbo].[FKC6101C91C4985D11]...';


GO
ALTER TABLE [dbo].[ProjectDocument] WITH NOCHECK
    ADD CONSTRAINT [FKC6101C91C4985D11] FOREIGN KEY ([Project_id]) REFERENCES [dbo].[Project] ([Id]);


GO
PRINT N'Creating [dbo].[FKF0FB9AEE2303E129]...';


GO
ALTER TABLE [dbo].[ReportPreset] WITH NOCHECK
    ADD CONSTRAINT [FKF0FB9AEE2303E129] FOREIGN KEY ([User_id]) REFERENCES [dbo].[User] ([Id]);


GO
PRINT N'Creating [dbo].[FKCFC6D85A445B4684]...';


GO
ALTER TABLE [dbo].[Project] WITH NOCHECK
    ADD CONSTRAINT [FKCFC6D85A445B4684] FOREIGN KEY ([Application_id]) REFERENCES [dbo].[Application] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Application] WITH CHECK CHECK CONSTRAINT [FK6AF3367D4487297D];

ALTER TABLE [dbo].[Booking] WITH CHECK CHECK CONSTRAINT [FK4DB400AFC4985D11];

ALTER TABLE [dbo].[Booking] WITH CHECK CHECK CONSTRAINT [FK4DB400AF2303E129];

ALTER TABLE [dbo].[Booking] WITH CHECK CHECK CONSTRAINT [FK4DB400AF91F7CAB3];

ALTER TABLE [dbo].[Correction] WITH CHECK CHECK CONSTRAINT [FK3232CB7E49E95258];

ALTER TABLE [dbo].[Document] WITH CHECK CHECK CONSTRAINT [FKEF5E95782303E129];

ALTER TABLE [dbo].[Document] WITH CHECK CHECK CONSTRAINT [FKEF5E9578C4985D11];

ALTER TABLE [dbo].[Invoice] WITH CHECK CHECK CONSTRAINT [FKDC60817C4985D11];

ALTER TABLE [dbo].[Invoice] WITH CHECK CHECK CONSTRAINT [FKDC60817FEFE956F];

ALTER TABLE [dbo].[InvoiceBooking] WITH CHECK CHECK CONSTRAINT [FK9D9576249E95258];

ALTER TABLE [dbo].[InvoiceBooking] WITH CHECK CHECK CONSTRAINT [FK9D95762864FB2B8];

ALTER TABLE [dbo].[InvoiceLine] WITH CHECK CHECK CONSTRAINT [FK64ABF92549E95258];

ALTER TABLE [dbo].[InvoiceLine] WITH CHECK CHECK CONSTRAINT [FK64ABF92591F7CAB3];

ALTER TABLE [dbo].[ProjectDocument] WITH CHECK CHECK CONSTRAINT [FKC6101C91D8CDF7D2];

ALTER TABLE [dbo].[ProjectDocument] WITH CHECK CHECK CONSTRAINT [FKC6101C91C4985D11];

ALTER TABLE [dbo].[ReportPreset] WITH CHECK CHECK CONSTRAINT [FKF0FB9AEE2303E129];

ALTER TABLE [dbo].[Project] WITH CHECK CHECK CONSTRAINT [FKCFC6D85A445B4684];


GO
PRINT N'Update complete.';


GO
